--INSERT INTO public.organization_type (id, name) VALUES
--(1, 'Coordination Center')
--,(2, 'Brigade')
--,(3, 'Surveillance Patrol')
--,(4, 'Mechanics')
--,(5, 'Vehicles')
--,(6, 'Local Entities');
